# Generated by Django 5.1.7 on 2026-09-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Home', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='accent',
            field=models.CharField(default='#9c4a2a', max_length=20),
        ),
    ]
